name: Release

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: echo ${{ github.sha }} > Release.txt
      - name: Make Installer
        run: make installer
      - name: Checksum Installer
        run: sha512sum installer.tar.gz > installer.sha512
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            installer.tar.gz
            installer.sha512